#Bates/Free20
#Bates/Free28
#Bates/Snack28
#Bates/Story28
#Bernstein/Children
#Bernstein/Interview
#Bliss
#Bloom70/Eric
#Bloom70/Gia
#Bohannon/Bax
#Bohannon/Nat
#Brent
#Carterette/
#Evans
#Garvey
#Gathercole
#Gleason/Dinner
#Gleason/Father
#Gleason/Mother
#HSLLD/HV1
#HSLLD/HV2
#HSLLD/HV3
#HSLLD/HV5
#HSLLD/HV7
#Haggerty
#Hall/BlackPro
#Hall/BlackWork
#Hall/WhitePro
#Hall/WhiteWork
#McCune/Alice
#McCune/Jase
#McCune/Laura
#McCune/Rick
#McMillan
#Morisset/Seattle
#Morisset/Topeka
#Morisset/UCLA
#NewEngland
#Peters
#Post
#Rollins
#Soderstrom
#Tardif
#Valian
#VanHouten/Threes
#VanHouten/Twos
#VanKleeck
#Warren
# Josh says not to use for Past Tense!

# $bloom70 = [ {:File=>"Bloom70/Peter/01.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>1, :Months=>9.7},
                  # {:File=>"Bloom70/Peter/02.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>1, :Months=>9.21},
                  # {:File=>"Bloom70/Peter/03.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>1, :Months=>10.15},
                  # {:File=>"Bloom70/Peter/04.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>1, :Months=>11.7},
                  # {:File=>"Bloom70/Peter/05.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>1, :Months=>11.21},
                  # {:File=>"Bloom70/Peter/06.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>0.7},
                  # {:File=>"Bloom70/Peter/07.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>0.7},
                  # {:File=>"Bloom70/Peter/08.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>1.21},
                  # {:File=>"Bloom70/Peter/09.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>2.14},
                  # {:File=>"Bloom70/Peter/10.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>3.0},
                  # {:File=>"Bloom70/Peter/11.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>3.21},
                  # {:File=>"Bloom70/Peter/12.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>4.14},
                  # {:File=>"Bloom70/Peter/13.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>5.0},
                  # {:File=>"Bloom70/Peter/14.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>5.21},
                  # {:File=>"Bloom70/Peter/15.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>6.14},
                  # {:File=>"Bloom70/Peter/16.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>7.14},
                  # {:File=>"Bloom70/Peter/17.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>8.14},
                  # {:File=>"Bloom70/Peter/18.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>9.14},
                  # {:File=>"Bloom70/Peter/19.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>2, :Months=>10.21},
                  # {:File=>"Bloom70/Peter/20.cha", :Child=>"Peter", :Corpus=>"Bloom70:Peter", :Years=>3, :Months=>1.21}]

# $bloom73 = [{:File=>"Bloom73/allison1.cha", :Child=>"Allison", :Corpus=>"Bloom73",:Years=>1, :Months=>4.21},
            # {:File=>"Bloom73/allison2.cha", :Child=>"Allison", :Corpus=>"Bloom73",:Years=>1, :Months=>7.14},
            # {:File=>"Bloom73/allison3.cha", :Child=>"Allison", :Corpus=>"Bloom73",:Years=>1, :Months=>8.21},
            # {:File=>"Bloom73/allison4.cha", :Child=>"Allison", :Corpus=>"Bloom73",:Years=>1, :Months=>10},
            # {:File=>"Bloom73/allison5.cha", :Child=>"Allison", :Corpus=>"Bloom73",:Years=>2, :Months=>4.7},
            # {:File=>"Bloom73/allison6.cha", :Child=>"Allison", :Corpus=>"Bloom73",:Years=>2, :Months=>10}]
                  
# $brown = [{:File=>"Brown/Adam/adam01.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>3.4},
                  # {:File=>"Brown/Adam/adam02.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>3.18},
                  # {:File=>"Brown/Adam/adam03.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>4.3},
                  # {:File=>"Brown/Adam/adam04.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>4.15},
                  # {:File=>"Brown/Adam/adam05.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>4.30},
                  # {:File=>"Brown/Adam/adam06.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>5.12},
                  # {:File=>"Brown/Adam/adam07.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>6.3},
                  # {:File=>"Brown/Adam/adam08.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>6.17},
                  # {:File=>"Brown/Adam/adam09.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>6.17},
                  # {:File=>"Brown/Adam/adam10.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>7.14},
                  # {:File=>"Brown/Adam/adam11.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>8.0},
                  # {:File=>"Brown/Adam/adam12.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>8.16},
                  # {:File=>"Brown/Adam/adam13.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>9.4},
                  # {:File=>"Brown/Adam/adam14.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>9.18},
                  # {:File=>"Brown/Adam/adam15.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>10.2},
                  # {:File=>"Brown/Adam/adam16.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>10.16},
                  # {:File=>"Brown/Adam/adam17.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>10.30},
                  # {:File=>"Brown/Adam/adam18.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>11.13},
                  # {:File=>"Brown/Adam/adam19.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>2, :Months=>11.28},
                  # {:File=>"Brown/Adam/adam20.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>0.11},
                  # {:File=>"Brown/Adam/adam21.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>0.25},
                  # {:File=>"Brown/Adam/adam22.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>1.9},
                  # {:File=>"Brown/Adam/adam23.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>1.26},
                  # {:File=>"Brown/Adam/adam24.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>2.9},
                  # {:File=>"Brown/Adam/adam25.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>2.21},
                  # {:File=>"Brown/Adam/adam26.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>3.4},
                  # {:File=>"Brown/Adam/adam27.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>3.18},
                  # {:File=>"Brown/Adam/adam28.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>4.1},
                  # {:File=>"Brown/Adam/adam29.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>4.18},
                  # {:File=>"Brown/Adam/adam30.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>5.0},
                  # {:File=>"Brown/Adam/adam31.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>5.15},
                  # {:File=>"Brown/Adam/adam32.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>6.9},
                  # {:File=>"Brown/Adam/adam33.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>5.29},
                  # {:File=>"Brown/Adam/adam34.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>7.7},
                  # {:File=>"Brown/Adam/adam35.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>8.0},
                  # {:File=>"Brown/Adam/adam36.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>8.14},
                  # {:File=>"Brown/Adam/adam37.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>8.26},
                  # {:File=>"Brown/Adam/adam38.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>9.16},
                  # {:File=>"Brown/Adam/adam39.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>10.15},
                  # {:File=>"Brown/Adam/adam40.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>11.0},
                  # {:File=>"Brown/Adam/adam41.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>3, :Months=>11.14},
                  # {:File=>"Brown/Adam/adam42.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>0.14},
                  # {:File=>"Brown/Adam/adam43.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>1.15},
                  # {:File=>"Brown/Adam/adam44.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>2.17},
                  # {:File=>"Brown/Adam/adam45.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>3.9},
                  # {:File=>"Brown/Adam/adam46.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>4.0},
                  # {:File=>"Brown/Adam/adam47.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>3.13},
                  # {:File=>"Brown/Adam/adam48.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>5.11},
                  # {:File=>"Brown/Adam/adam49.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>6.24},
                  # {:File=>"Brown/Adam/adam50.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>7.0},
                  # {:File=>"Brown/Adam/adam51.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>7.29},
                  # {:File=>"Brown/Adam/adam52.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>5, :Months=>2.12},
                  # {:File=>"Brown/Adam/adam53.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>9.2},
                  # {:File=>"Brown/Adam/adam54.cha", :Child=>"Adam",:Corpus=>"Brown:Adam", :Years=>4, :Months=>10.2},
                  # {:File=>"Brown/Adam/adam55.cha", :Child=>"Adam", :Corpus=>"Brown:Adam", :Years=>4, :Months=>10.23},
                  # {:File=>"Brown/Eve/eve01.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>6},
                  # {:File=>"Brown/Eve/eve02.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>6},
                  # {:File=>"Brown/Eve/eve03.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>7},
                  # {:File=>"Brown/Eve/eve04.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>7},
                  # {:File=>"Brown/Eve/eve05.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>8},
                  # {:File=>"Brown/Eve/eve06.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>9},
                  # {:File=>"Brown/Eve/eve07.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>9},
                  # {:File=>"Brown/Eve/eve08.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>9},
                  # {:File=>"Brown/Eve/eve09.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>10},
                  # {:File=>"Brown/Eve/eve10.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>10},
                  # {:File=>"Brown/Eve/eve11.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>11},
                  # {:File=>"Brown/Eve/eve12.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>11},
                  # {:File=>"Brown/Eve/eve13.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>12},
                  # {:File=>"Brown/Eve/eve14.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>0},
                  # {:File=>"Brown/Eve/eve15.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>1},
                  # {:File=>"Brown/Eve/eve16.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>1},
                  # {:File=>"Brown/Eve/eve17.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>2},
                  # {:File=>"Brown/Eve/eve18.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>2},
                  # {:File=>"Brown/Eve/eve19.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>3},
                  # {:File=>"Brown/Eve/eve20.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>3},
                  # {:File=>"Brown/Sarah/sarah001.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.5},
                  # {:File=>"Brown/Sarah/sarah002.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.7},
                  # {:File=>"Brown/Sarah/sarah003.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.19},
                  # {:File=>"Brown/Sarah/sarah004.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.22},
                  # {:File=>"Brown/Sarah/sarah005.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.26},
                  # {:File=>"Brown/Sarah/sarah006.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.28},
                  # {:File=>"Brown/Sarah/sarah007.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>4.10},
                  # {:File=>"Brown/Sarah/sarah008.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>4.12},
                  # {:File=>"Brown/Sarah/sarah009.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>4.17},
                  # {:File=>"Brown/Sarah/sarah010.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>4.19},
                  # {:File=>"Brown/Sarah/sarah011.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>4.26},
                  # {:File=>"Brown/Sarah/sarah012.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>5.7},
                  # {:File=>"Brown/Sarah/sarah013.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>5.15},
                  # {:File=>"Brown/Sarah/sarah014.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>5.25},
                  # {:File=>"Brown/Sarah/sarah015.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>5.30},
                  # {:File=>"Brown/Sarah/sarah016.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>6.4},
                  # {:File=>"Brown/Sarah/sarah017.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>6.13},
                  # {:File=>"Brown/Sarah/sarah018.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>6.20},
                  # {:File=>"Brown/Sarah/sarah019.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>6.30},
                  # {:File=>"Brown/Sarah/sarah020.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>7.5},
                  # {:File=>"Brown/Sarah/sarah021.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>7.12},
                  # {:File=>"Brown/Sarah/sarah022.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>7.18},
                  # {:File=>"Brown/Sarah/sarah023.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>7.28},
                  # {:File=>"Brown/Sarah/sarah024.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>8.2},
                  # {:File=>"Brown/Sarah/sarah025.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>8.25},
                  # {:File=>"Brown/Sarah/sarah026.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>8.25},
                  # {:File=>"Brown/Sarah/sarah027.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>9.0},
                  # {:File=>"Brown/Sarah/sarah028.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>9.6},
                  # {:File=>"Brown/Sarah/sarah029.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>9.14},
                  # {:File=>"Brown/Sarah/sarah010.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>9.20},
                  # {:File=>"Brown/Sarah/sarah031.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>9.29},
                  # {:File=>"Brown/Sarah/sarah032.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>10.5},
                  # {:File=>"Brown/Sarah/sarah033.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>10.11},
                  # {:File=>"Brown/Sarah/sarah034.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>10.20},
                  # {:File=>"Brown/Sarah/sarah035.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>10.24},
                  # {:File=>"Brown/Sarah/sarah036.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>11.2},
                  # {:File=>"Brown/Sarah/sarah037.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>11.17},
                  # {:File=>"Brown/Sarah/sarah038.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>11.23},
                  # {:File=>"Brown/Sarah/sarah039.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>11.30},
                  # {:File=>"Brown/Sarah/sarah040.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>0.18},
                  # {:File=>"Brown/Sarah/sarah041.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>0.18},
                  # {:File=>"Brown/Sarah/sarah042.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>0.27},
                  # {:File=>"Brown/Sarah/sarah043.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>1.3},
                  # {:File=>"Brown/Sarah/sarah044.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>1.10},
                  # {:File=>"Brown/Sarah/sarah045.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>1.17},
                  # {:File=>"Brown/Sarah/sarah046.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>1.24},
                  # {:File=>"Brown/Sarah/sarah047.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>2.2},
                  # {:File=>"Brown/Sarah/sarah048.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>2.10},
                  # {:File=>"Brown/Sarah/sarah049.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>2.16},
                  # {:File=>"Brown/Sarah/sarah050.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>2.23},
                  # {:File=>"Brown/Sarah/sarah051.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>3.7},
                  # {:File=>"Brown/Sarah/sarah052.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>3.7},
                  # {:File=>"Brown/Sarah/sarah053.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>3.13},
                  # {:File=>"Brown/Sarah/sarah054.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>3.20},
                  # {:File=>"Brown/Sarah/sarah055.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>3.28},
                  # {:File=>"Brown/Sarah/sarah056.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>4.1},
                  # {:File=>"Brown/Sarah/sarah057.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>4.9},
                  # {:File=>"Brown/Sarah/sarah058.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>4.16},
                  # {:File=>"Brown/Sarah/sarah059.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>4.26},
                  # {:File=>"Brown/Sarah/sarah060.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>5.1},
                  # {:File=>"Brown/Sarah/sarah061.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>5.7},
                  # {:File=>"Brown/Sarah/sarah062.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>5.13},
                  # {:File=>"Brown/Sarah/sarah063.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>5.20},
                  # {:File=>"Brown/Sarah/sarah064.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>6.6},
                  # {:File=>"Brown/Sarah/sarah065.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>6.16},
                  # {:File=>"Brown/Sarah/sarah066.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>6.23},
                  # {:File=>"Brown/Sarah/sarah067.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>6.30},
                  # {:File=>"Brown/Sarah/sarah068.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>7.9},
                  # {:File=>"Brown/Sarah/sarah069.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>7.16},
                  # {:File=>"Brown/Sarah/sarah070.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>7.23},
                  # {:File=>"Brown/Sarah/sarah071.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>7.30},
                  # {:File=>"Brown/Sarah/sarah072.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>8.6},
                  # {:File=>"Brown/Sarah/sarah073.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>8.12},
                  # {:File=>"Brown/Sarah/sarah074.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>8.20},
                  # {:File=>"Brown/Sarah/sarah075.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>8.27},
                  # {:File=>"Brown/Sarah/sarah076.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>9.3},
                  # {:File=>"Brown/Sarah/sarah077.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>9.18},
                  # {:File=>"Brown/Sarah/sarah078.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>9.26},
                  # {:File=>"Brown/Sarah/sarah079.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>9.26},
                  # {:File=>"Brown/Sarah/sarah080.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>10.1},
                  # {:File=>"Brown/Sarah/sarah081.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>10.9},
                  # {:File=>"Brown/Sarah/sarah082.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>10.16},
                  # {:File=>"Brown/Sarah/sarah083.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>10.30},
                  # {:File=>"Brown/Sarah/sarah084.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>11.9},
                  # {:File=>"Brown/Sarah/sarah085.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>11.16},
                  # {:File=>"Brown/Sarah/sarah086.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>11.29},
                  # {:File=>"Brown/Sarah/sarah087.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>0.5},
                  # {:File=>"Brown/Sarah/sarah088.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>0.14},
                  # {:File=>"Brown/Sarah/sarah089.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>0.28},
                  # {:File=>"Brown/Sarah/sarah090.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>1.4},
                  # {:File=>"Brown/Sarah/sarah091.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>1.11},
                  # {:File=>"Brown/Sarah/sarah092.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>1.18},
                  # {:File=>"Brown/Sarah/sarah093.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>1.28},
                  # {:File=>"Brown/Sarah/sarah094.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>2.1},
                  # {:File=>"Brown/Sarah/sarah095.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>2.9},
                  # {:File=>"Brown/Sarah/sarah096.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>2.16},
                  # {:File=>"Brown/Sarah/sarah097.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>2.23},
                  # {:File=>"Brown/Sarah/sarah098.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>2.28},
                  # {:File=>"Brown/Sarah/sarah099.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>3.7},
                  # {:File=>"Brown/Sarah/sarah100.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>3.13},
                  # {:File=>"Brown/Sarah/sarah101.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>3.19},
                  # {:File=>"Brown/Sarah/sarah102.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>3.26},
                  # {:File=>"Brown/Sarah/sarah103.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>4.1},
                  # {:File=>"Brown/Sarah/sarah104.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>4.11},
                  # {:File=>"Brown/Sarah/sarah105.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>4.18},
                  # {:File=>"Brown/Sarah/sarah106.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>4.25},
                  # {:File=>"Brown/Sarah/sarah107.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>5.4},
                  # {:File=>"Brown/Sarah/sarah108.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>5.8},
                  # {:File=>"Brown/Sarah/sarah109.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>5.14},
                  # {:File=>"Brown/Sarah/sarah110.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>5.22},
                  # {:File=>"Brown/Sarah/sarah111.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>5.29},
                  # {:File=>"Brown/Sarah/sarah112.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>6.5},
                  # {:File=>"Brown/Sarah/sarah113.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>6.11},
                  # {:File=>"Brown/Sarah/sarah114.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>6.17},
                  # {:File=>"Brown/Sarah/sarah115.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>6.24},
                  # {:File=>"Brown/Sarah/sarah116.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>7.0},
                  # {:File=>"Brown/Sarah/sarah117.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>7.11},
                  # {:File=>"Brown/Sarah/sarah118.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>7.17},
                  # {:File=>"Brown/Sarah/sarah119.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>7.24},
                  # {:File=>"Brown/Sarah/sarah120.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>8.7},
                  # {:File=>"Brown/Sarah/sarah121.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>8.13},
                  # {:File=>"Brown/Sarah/sarah122.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>8.20},
                  # {:File=>"Brown/Sarah/sarah123.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>9.4},
                  # {:File=>"Brown/Sarah/sarah124.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>9.12},
                  # {:File=>"Brown/Sarah/sarah125.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>9.19},
                  # {:File=>"Brown/Sarah/sarah126.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>9.26},
                  # {:File=>"Brown/Sarah/sarah127.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>10.6},
                  # {:File=>"Brown/Sarah/sarah128.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>10.21},
                  # {:File=>"Brown/Sarah/sarah129.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>10.27},
                  # {:File=>"Brown/Sarah/sarah130.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>11.4},
                  # {:File=>"Brown/Sarah/sarah131.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>11.13},
                  # {:File=>"Brown/Sarah/sarah132.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>11.19},
                  # {:File=>"Brown/Sarah/sarah133.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>11.26},
                  # {:File=>"Brown/Sarah/sarah134.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>0.2},
                  # {:File=>"Brown/Sarah/sarah135.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>0.10},
                  # {:File=>"Brown/Sarah/sarah136.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>0.16},
                  # {:File=>"Brown/Sarah/sarah137.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>0.25},
                  # {:File=>"Brown/Sarah/sarah138.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>0.30},
                  # {:File=>"Brown/Sarah/sarah139.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>1.6}]

$brown = [
                  {:File=>"Brown/Eve/eve01.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>6},
                  {:File=>"Brown/Eve/eve02.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>6},
                  {:File=>"Brown/Eve/eve03.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>7},
                  {:File=>"Brown/Eve/eve04.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>7},
                  {:File=>"Brown/Eve/eve05.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>8},
                  {:File=>"Brown/Eve/eve06.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>9},
                  {:File=>"Brown/Eve/eve07.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>9},
                  {:File=>"Brown/Eve/eve08.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>9},
                  {:File=>"Brown/Eve/eve09.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>10},
                  {:File=>"Brown/Eve/eve10.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>10},
                  {:File=>"Brown/Eve/eve11.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>11},
                  {:File=>"Brown/Eve/eve12.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>11},
                  {:File=>"Brown/Eve/eve13.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>1, :Months=>12},
                  {:File=>"Brown/Eve/eve14.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>0},
                  {:File=>"Brown/Eve/eve15.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>1},
                  {:File=>"Brown/Eve/eve16.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>1},
                  {:File=>"Brown/Eve/eve17.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>2},
                  {:File=>"Brown/Eve/eve18.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>2},
                  {:File=>"Brown/Eve/eve19.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>3},
                  {:File=>"Brown/Eve/eve20.cha", :Child=>"Eve", :Corpus=>"Brown:Eve", :Years=>2, :Months=>3},
                  {:File=>"Brown/Sarah/sarah001.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.5},
                  {:File=>"Brown/Sarah/sarah002.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.7},
                  {:File=>"Brown/Sarah/sarah003.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.19},
                  {:File=>"Brown/Sarah/sarah004.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.22},
                  {:File=>"Brown/Sarah/sarah005.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.26},
                  {:File=>"Brown/Sarah/sarah006.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>3.28},
                  {:File=>"Brown/Sarah/sarah007.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>4.10},
                  {:File=>"Brown/Sarah/sarah008.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>4.12},
                  {:File=>"Brown/Sarah/sarah009.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>4.17},
                  {:File=>"Brown/Sarah/sarah010.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>4.19},
                  {:File=>"Brown/Sarah/sarah011.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>4.26},
                  {:File=>"Brown/Sarah/sarah012.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>5.7},
                  {:File=>"Brown/Sarah/sarah013.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>5.15},
                  {:File=>"Brown/Sarah/sarah014.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>5.25},
                  {:File=>"Brown/Sarah/sarah015.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>5.30},
                  {:File=>"Brown/Sarah/sarah016.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>6.4},
                  {:File=>"Brown/Sarah/sarah017.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>6.13},
                  {:File=>"Brown/Sarah/sarah018.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>6.20},
                  {:File=>"Brown/Sarah/sarah019.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>6.30},
                  {:File=>"Brown/Sarah/sarah020.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>7.5},
                  {:File=>"Brown/Sarah/sarah021.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>7.12},
                  {:File=>"Brown/Sarah/sarah022.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>7.18},
                  {:File=>"Brown/Sarah/sarah023.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>7.28},
                  {:File=>"Brown/Sarah/sarah024.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>8.2},
                  {:File=>"Brown/Sarah/sarah025.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>8.25},
                  {:File=>"Brown/Sarah/sarah026.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>8.25},
                  {:File=>"Brown/Sarah/sarah027.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>9.0},
                  {:File=>"Brown/Sarah/sarah028.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>9.6},
                  {:File=>"Brown/Sarah/sarah029.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>9.14},
                  {:File=>"Brown/Sarah/sarah010.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>9.20},
                  {:File=>"Brown/Sarah/sarah031.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>9.29},
                  {:File=>"Brown/Sarah/sarah032.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>10.5},
                  {:File=>"Brown/Sarah/sarah033.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>10.11},
                  {:File=>"Brown/Sarah/sarah034.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>10.20},
                  {:File=>"Brown/Sarah/sarah035.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>10.24},
                  {:File=>"Brown/Sarah/sarah036.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>11.2},
                  {:File=>"Brown/Sarah/sarah037.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>11.17},
                  {:File=>"Brown/Sarah/sarah038.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>11.23},
                  {:File=>"Brown/Sarah/sarah039.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>2, :Months=>11.30},
                  {:File=>"Brown/Sarah/sarah040.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>0.18},
                  {:File=>"Brown/Sarah/sarah041.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>0.18},
                  {:File=>"Brown/Sarah/sarah042.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>0.27},
                  {:File=>"Brown/Sarah/sarah043.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>1.3},
                  {:File=>"Brown/Sarah/sarah044.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>1.10},
                  {:File=>"Brown/Sarah/sarah045.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>1.17},
                  {:File=>"Brown/Sarah/sarah046.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>1.24},
                  {:File=>"Brown/Sarah/sarah047.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>2.2},
                  {:File=>"Brown/Sarah/sarah048.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>2.10},
                  {:File=>"Brown/Sarah/sarah049.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>2.16},
                  {:File=>"Brown/Sarah/sarah050.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>2.23},
                  {:File=>"Brown/Sarah/sarah051.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>3.7},
                  {:File=>"Brown/Sarah/sarah052.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>3.7},
                  {:File=>"Brown/Sarah/sarah053.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>3.13},
                  {:File=>"Brown/Sarah/sarah054.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>3.20},
                  {:File=>"Brown/Sarah/sarah055.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>3.28},
                  {:File=>"Brown/Sarah/sarah056.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>4.1},
                  {:File=>"Brown/Sarah/sarah057.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>4.9},
                  {:File=>"Brown/Sarah/sarah058.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>4.16},
                  {:File=>"Brown/Sarah/sarah059.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>4.26},
                  {:File=>"Brown/Sarah/sarah060.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>5.1},
                  {:File=>"Brown/Sarah/sarah061.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>5.7},
                  {:File=>"Brown/Sarah/sarah062.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>5.13},
                  {:File=>"Brown/Sarah/sarah063.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>5.20},
                  {:File=>"Brown/Sarah/sarah064.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>6.6},
                  {:File=>"Brown/Sarah/sarah065.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>6.16},
                  {:File=>"Brown/Sarah/sarah066.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>6.23},
                  {:File=>"Brown/Sarah/sarah067.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>6.30},
                  {:File=>"Brown/Sarah/sarah068.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>7.9},
                  {:File=>"Brown/Sarah/sarah069.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>7.16},
                  {:File=>"Brown/Sarah/sarah070.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>7.23},
                  {:File=>"Brown/Sarah/sarah071.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>7.30},
                  {:File=>"Brown/Sarah/sarah072.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>8.6},
                  {:File=>"Brown/Sarah/sarah073.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>8.12},
                  {:File=>"Brown/Sarah/sarah074.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>8.20},
                  {:File=>"Brown/Sarah/sarah075.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>8.27},
                  {:File=>"Brown/Sarah/sarah076.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>9.3},
                  {:File=>"Brown/Sarah/sarah077.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>9.18},
                  {:File=>"Brown/Sarah/sarah078.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>9.26},
                  {:File=>"Brown/Sarah/sarah079.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>9.26},
                  {:File=>"Brown/Sarah/sarah080.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>10.1},
                  {:File=>"Brown/Sarah/sarah081.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>10.9},
                  {:File=>"Brown/Sarah/sarah082.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>10.16},
                  {:File=>"Brown/Sarah/sarah083.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>10.30},
                  {:File=>"Brown/Sarah/sarah084.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>11.9},
                  {:File=>"Brown/Sarah/sarah085.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>11.16},
                  {:File=>"Brown/Sarah/sarah086.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>3, :Months=>11.29},
                  {:File=>"Brown/Sarah/sarah087.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>0.5},
                  {:File=>"Brown/Sarah/sarah088.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>0.14},
                  {:File=>"Brown/Sarah/sarah089.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>0.28},
                  {:File=>"Brown/Sarah/sarah090.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>1.4},
                  {:File=>"Brown/Sarah/sarah091.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>1.11},
                  {:File=>"Brown/Sarah/sarah092.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>1.18},
                  {:File=>"Brown/Sarah/sarah093.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>1.28},
                  {:File=>"Brown/Sarah/sarah094.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>2.1},
                  {:File=>"Brown/Sarah/sarah095.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>2.9},
                  {:File=>"Brown/Sarah/sarah096.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>2.16},
                  {:File=>"Brown/Sarah/sarah097.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>2.23},
                  {:File=>"Brown/Sarah/sarah098.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>2.28},
                  {:File=>"Brown/Sarah/sarah099.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>3.7},
                  {:File=>"Brown/Sarah/sarah100.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>3.13},
                  {:File=>"Brown/Sarah/sarah101.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>3.19},
                  {:File=>"Brown/Sarah/sarah102.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>3.26},
                  {:File=>"Brown/Sarah/sarah103.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>4.1},
                  {:File=>"Brown/Sarah/sarah104.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>4.11},
                  {:File=>"Brown/Sarah/sarah105.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>4.18},
                  {:File=>"Brown/Sarah/sarah106.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>4.25},
                  {:File=>"Brown/Sarah/sarah107.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>5.4},
                  {:File=>"Brown/Sarah/sarah108.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>5.8},
                  {:File=>"Brown/Sarah/sarah109.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>5.14},
                  {:File=>"Brown/Sarah/sarah110.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>5.22},
                  {:File=>"Brown/Sarah/sarah111.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>5.29},
                  {:File=>"Brown/Sarah/sarah112.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>6.5},
                  {:File=>"Brown/Sarah/sarah113.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>6.11},
                  {:File=>"Brown/Sarah/sarah114.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>6.17},
                  {:File=>"Brown/Sarah/sarah115.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>6.24},
                  {:File=>"Brown/Sarah/sarah116.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>7.0},
                  {:File=>"Brown/Sarah/sarah117.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>7.11},
                  {:File=>"Brown/Sarah/sarah118.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>7.17},
                  {:File=>"Brown/Sarah/sarah119.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>7.24},
                  {:File=>"Brown/Sarah/sarah120.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>8.7},
                  {:File=>"Brown/Sarah/sarah121.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>8.13},
                  {:File=>"Brown/Sarah/sarah122.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>8.20},
                  {:File=>"Brown/Sarah/sarah123.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>9.4},
                  {:File=>"Brown/Sarah/sarah124.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>9.12},
                  {:File=>"Brown/Sarah/sarah125.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>9.19},
                  {:File=>"Brown/Sarah/sarah126.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>9.26},
                  {:File=>"Brown/Sarah/sarah127.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>10.6},
                  {:File=>"Brown/Sarah/sarah128.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>10.21},
                  {:File=>"Brown/Sarah/sarah129.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>10.27},
                  {:File=>"Brown/Sarah/sarah130.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>11.4},
                  {:File=>"Brown/Sarah/sarah131.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>11.13},
                  {:File=>"Brown/Sarah/sarah132.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>11.19},
                  {:File=>"Brown/Sarah/sarah133.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>4, :Months=>11.26},
                  {:File=>"Brown/Sarah/sarah134.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>0.2},
                  {:File=>"Brown/Sarah/sarah135.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>0.10},
                  {:File=>"Brown/Sarah/sarah136.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>0.16},
                  {:File=>"Brown/Sarah/sarah137.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>0.25},
                  {:File=>"Brown/Sarah/sarah138.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>0.30},
                  {:File=>"Brown/Sarah/sarah139.cha", :Child=>"Sarah", :Corpus=>"Brown:Sarah", :Years=>5, :Months=>1.6}]

$childes_files = $brown
